// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO38qWwJSNHivHJk_qx7smrPW9Wg2QK14',
    appId: '1:231787513563:web:e3a6edff241fc5d8192efe',
    messagingSenderId: '231787513563',
    projectId: 'ltw-cp',
    authDomain: 'ltw-cp.firebaseapp.com',
    storageBucket: 'ltw-cp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9li7Si9hQHrmKBu8FqCrr5h4hvu81Pc',
    appId: '1:231787513563:android:1f32f0520017e749192efe',
    messagingSenderId: '231787513563',
    projectId: 'ltw-cp',
    storageBucket: 'ltw-cp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkrlK0BwaynuZUKZ-dLISf0vbuV4hnIg',
    appId: '1:231787513563:ios:6ec6fd533a9c1974192efe',
    messagingSenderId: '231787513563',
    projectId: 'ltw-cp',
    storageBucket: 'ltw-cp.appspot.com',
    iosClientId: '231787513563-nvlv1dnft890fh8lo8ilt49cu3skskob.apps.googleusercontent.com',
    iosBundleId: 'com.dc143c.ltwcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkrlK0BwaynuZUKZ-dLISf0vbuV4hnIg',
    appId: '1:231787513563:ios:6ec6fd533a9c1974192efe',
    messagingSenderId: '231787513563',
    projectId: 'ltw-cp',
    storageBucket: 'ltw-cp.appspot.com',
    iosClientId: '231787513563-nvlv1dnft890fh8lo8ilt49cu3skskob.apps.googleusercontent.com',
    iosBundleId: 'com.dc143c.ltwcp',
  );
}
